### Site info:
title: Gruppo podistico amici di Caleppio
author: Andrea Rivadossi
email: riva.andrea.web@gmail.com
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "gruppo podistico"
baseurl:
locale: it_IT

### Personal info and site tools info:
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Lijia Yu. I made the Freshman21 theme. Please enjoy it. # these are shown on aboutme-sidebar.
aboutme_photo: https://scontent-mxp1-1.xx.fbcdn.net/v/t1.0-9/10411977_800853253266775_8607534746513888623_n.png?_nc_cat=0&oh=170fb186e5ae3bbb57b5c01ad3ba342e&oe=5B9F5A14
google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "it" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"
    en:
      Aboutme: "Chi siamo"
      Archives: "Archivio"
      Blogroll: "Blog"
      Categories: "Categorie"
      Copyright_Notice: "Copyright"
      Recent_Posts: "News recenti"
      Tags: "Tags"
      Previous: "Vecchi"
      Next: "Nuovi"
      PostedInCategories: "Pubblicato in"
      Taggedwith: ""
      PostDate: "il "
      Google_search: "Cerca"
      Home: "Home"
      About: "Chi siamo"
      Guestbook: "Guestbook"
      Subscribe: "Iscriviti"

### Build settings
markdown: kramdown
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
